from collections import namedtuple

IMAGING_SERVER_RESOURCE_PATIENT = 'Patient'
IMAGING_SERVER_RESOURCE_STUDY = 'Study'
IMAGING_SERVER_RESOURCE_SERIES = 'Series'
IMAGING_SERVER_RESOURCE_IMAGE = 'Instance'
IMAGING_SERVER_RESOURCE_REPORT = 'Report'

IMAGING_SERVER_RESOURCE_SUPPORTED = [
	IMAGING_SERVER_RESOURCE_PATIENT, IMAGING_SERVER_RESOURCE_STUDY, IMAGING_SERVER_RESOURCE_SERIES]

DCMHEADER_PATIENT_ID = 'PatientID'
DCMHEADER_PATIENT_NAME = 'PatientName'
DCMHEADER_PATIENT_SEX = 'PatientSex'
DCMHEADER_PATIENT_BIRTHDATE = 'PatientBirthDate'
DCMHEADER_PATIENT_COMMENTS = 'PatientComments'

DCMHEADER_STUDY_INSTANCE_UID = 'StudyInstanceUID'
DCMHEADER_STUDY_ID = 'StudyID'
DCMHEADER_STUDY_DESCRIPTION = 'StudyDescription'

DCMHEADER_SERIES_INSTANCE_UID = 'SeriesInstanceUID'
DCMHEADER_SERIES_DESCRIPTION = 'SeriesDescription'

DCMHEADER_REQUESTED_PROCEDURE_ID = 'RequestedProcedureID'
DCMHEADER_CLINICAL_TRIAL_PROTOCOLID = 'ClinicalTrialProtocolID'
DCMHEADER_CLINICAL_TRIAL_SUBJECTID = 'ClinicalTrialSubjectID'
DCMHEADER_CLINICAL_TRIAL_SPONSOR = 'ClinicalTrialSponsorName'
DCMHEADER_IMAGE_POSITION_PATIENT = 'ImagePositionPatient'
DCMHEADER_IMAGE_ORIENTATION_PATIENT = 'ImageOrientationPatient'
DCMHEADER_PATIENT_POSITION = 'PatientPosition'
DCMHEADER_MODALITY = 'Modality'

DCMHEADER_SR_PERTINENT_OTHER_EVIDENCE_SEQUENCE = 'PertinentOtherEvidenceSequence'
DCMHEADER_SR_REF_SERIES_SEQ = 'ReferencedSeriesSequence'
DCMHEADER_SR_REF_INSTANCE_SEQ = 'ReferencedInstanceSequence'
DCMHEADER_SR_REF_SOP_SEQ = 'ReferencedSOPSequence'
DCMHEADER_SR_DERIVATION_IMAGE_SEQ = 'DerivationImageSequence'
DCMHEADER_SR_SOURCE_IMAGE_SEQ = 'SourceImageSequence'

DCMHEADER_SR_REF_INSTANCE_UID = 'ReferencedSOPInstanceUID'

DCM_PATIENT_POSITION_HFP = 'HFP'
DCM_PATIENT_POSITION_HFS = 'HFS'
DCM_PATIENT_POSITION_HFDR = 'HDFR'
DCM_PATIENT_POSITION_HFDL = 'HFDL'
DCM_PATIENT_POSITION_FFP = 'FFP'
DCM_PATIENT_POSITION_FFS = 'FFS'
DCM_PATIENT_POSITION_FFDR = 'FFDR'
DCM_PATIENT_POSITION_FFDL = 'FFDL'

DCM_PATIENT_POSITION_LABELS = {
	DCM_PATIENT_POSITION_HFP: 'Head First Prone',
	DCM_PATIENT_POSITION_HFS: 'Head First Supine',
	DCM_PATIENT_POSITION_HFDR: 'Head First Decubitus Right',
	DCM_PATIENT_POSITION_HFDL: 'Head First Decubitus Left',
	DCM_PATIENT_POSITION_FFP: 'Feet First Prone',
	DCM_PATIENT_POSITION_FFS: 'Feet First Supine',
	DCM_PATIENT_POSITION_FFDR: 'Feet First Decubitus Right',
	DCM_PATIENT_POSITION_FFDL: 'Feet First Decubitus Left',
}

DCM_DATETIME_STRFORMAT = '%Y%m%d%H%M%S.%f'
DCM_DATE_STRFORMAT = '%Y%m%d'
DCM_TIME_STRFORMAT = '%H%M%S.%f'
DCM_TIME_STRFORMAT_ALT1 = '%H%M%S'


DCM_FILE_EXTENSION = 'dcm'
DCM_EXTENSIONS_DEFAULT = ['*.dcm', '*.DCM', '*.DICOM', '*.dicom', 'IM*']
DCM_EXTENSIONS_ALL_FILES = ['*']
DCM_MODALITY_MR = 'MR'
DCM_MODALITIES_MRI = ['MR', 'MRI', 'MR\\SD']

DCM_MODALITY_SR = 'SR'
DCM_MODALITY_SEG = 'SEG'


# Environment variable names
SONADOR_ACCESS_ID = 'SONADOR_ACCESS_ID'
SONADOR_SECRET_KEY = 'SONADOR_SECRET_KEY'
SONADOR_URL = 'SONADOR_URL'
SONADOR_APITOKEN = 'SONADOR_APITOKEN'
SONADOR_INTERNAL_DNS = 'SONADOR_INTERNAL_DNS'
SONADOR_IMAGING_SERVER = 'SONADOR_IMAGING_SERVER'
SONADOR_SERVICE_CLIENT_ID = 'SONADOR_SERVICE_CLIENT_ID'


# Functional testing globals
from client.utils.logs import LOGGING_LEVELS

TESTING_VERBOSITY = {
	'debug': 3,
	'info': 2,
	'warning': 1,
	'error': 0,
	'critical': 0,
}


# Header cache constants and data classes
DCM_CONTENT_TYPE = 'application/octet-stream'

DicomMetaKey = namedtuple('DicomMetaKey', ('resource', 'header', 'uid'))
DicomMeta = namedtuple('DicomMeta', ('description', 'modality'))
