import re
from collections import namedtuple

from pydicom.sr.codedict import codes as dcmcodes

from highdicom.version import __version__ as HIGHDICOM_VERSION
from highdicom.sr.templates import Code, CodedConcept


SONADOR_MANUFACTURER = 'Sonador'
HIGHDICOM_MANUFACTURER = 'HIGHDICOM'
SONADOR_DEVELOPMENT_TEAM = '%s Development Team' % SONADOR_MANUFACTURER
HIGHDICOM_DEVELOPMENT_TEAM = '%s Development Team' % HIGHDICOM_MANUFACTURER

SONADOR_CLIENT = '%s-Client' % SONADOR_MANUFACTURER
SONADOR_CLIENT_DESCRIPTION = 'Client library for working with medical imaging data stored in Sonador/Orthanc.'
SONADOR_SCHEME_VERSION = '0.1'

SONADOR_SEG = 'Sonador-SEG'
SONADOR_SEG_DESCRIPTION = '%s implements tools for working with segmentation data' % SONADOR_SEG
DCMSR_SONADOR_SEG = Code(SONADOR_SEG, SONADOR_CLIENT, SONADOR_SEG_DESCRIPTION,
	scheme_version=SONADOR_SCHEME_VERSION)

SONADOR_SR = 'Sonador-SR'
SONADOR_SR_DESCRIPTION = '%s implements tools for working with structured reporting data' % SONADOR_SR
DCMSR_SONADOR_SR = Code(SONADOR_SR, SONADOR_CLIENT, SONADOR_SR_DESCRIPTION,
	scheme_version=SONADOR_SCHEME_VERSION)



IMAGING_SERVER_RESOURCE_PATIENT = 'Patient'
IMAGING_SERVER_RESOURCE_STUDY = 'Study'
IMAGING_SERVER_RESOURCE_SERIES = 'Series'
IMAGING_SERVER_RESOURCE_IMAGE = 'Instance'
IMAGING_SERVER_RESOURCE_REPORT = 'Report'

IMAGING_SERVER_UID_REGEX = re.compile(r'(.+)?(?P<uid>([0-9a-fA-F]{8}\-?){5})(.+)?')

IMAGING_SERVER_RESOURCE_SUPPORTED = [
	IMAGING_SERVER_RESOURCE_PATIENT, IMAGING_SERVER_RESOURCE_STUDY, IMAGING_SERVER_RESOURCE_SERIES]

IMAGING_SERVER_LAST_UPDATE = 'LastUpdate'
IMAGING_SERVER_DICOMTAGS_SIGNATURE = 'MainDicomTagsSignature'


DCM_VERSION_2008 = '2008'
DCM_VERSION_2017c = '2017c'
DCM_VERSION_2021b = '2021b'

DCMCODE_PATIENT_ID = ('0010', '0020')
DCMHEADER_PATIENT_ID = 'PatientID'

DCMCODE_PATIENT_NAME = ('0010','0010')
DCMHEADER_PATIENT_NAME = 'PatientName'

DCMHEADER_PATIENT_SEX = 'PatientSex'

DCMCODE_PATIENT_BIRTHDATE = ('0010', '0030')
DCMHEADER_PATIENT_BIRTHDATE = 'PatientBirthDate'

DCMHEADER_PATIENT_COMMENTS = 'PatientComments'

DCMHEADER_PATIENT_OTHERIDS = 'OtherPatientIDs'

DCMCODE_STUDY_INSTANCE_UID = ('0020', '000D')
DCMHEADER_STUDY_INSTANCE_UID = 'StudyInstanceUID'

DCMCODE_STUDY_ID = ('0020', '0010')
DCMHEADER_STUDY_ID = 'StudyID'

DCMCODE_STUDY_DATE = ('0008', '0020')
DCMHEADER_STUDY_DATE = 'StudyDate'

DCMCODE_STUDY_TIME = ('0008', '0030')
DCMHEADER_STUDY_TIME = 'StudyTime'

DCMCODE_ACCESSION_NUMBER = ('0008', '0050')
DCMHEADER_ACCESSION_NUMBER = 'AccessionNumber'

DCMCODE_STUDY_DESCRIPTION = ('0008', '1030')
DCMHEADER_STUDY_DESCRIPTION = 'StudyDescription'

DCMCODE_SERIES_INSTANCE_UID = ('0020', '000e')
DCMHEADER_SERIES_INSTANCE_UID = 'SeriesInstanceUID'

DCMCODE_SERIES_DATE = ('0008', '0021')
DCMHEADER_SERIES_DATE = 'SeriesDate'

DCMCODE_SERIES_TIME = ('0008', '0031')
DCMHEADER_SERIES_TIME = 'SeriesTime'

DCMCODE_SERIES_DESCRIPTION = ('0008', '103e')
DCMHEADER_SERIES_DESCRIPTION = 'SeriesDescription'

DCMCODE_IMAGE_TYPE = ('0008', '0008')
DCMHEADER_IMAGE_TYPE = 'ImageType'

DCM_IMAGE_TYPE_DERIVED = 'Derived\\Secondary'

DCMHEADER_INSTITUTION_NAME = 'InstitutionName'
DCMHEADER_REQUESTING_PHYSICIAN = 'RequestingPhysician'
DCMHEADER_REFERRING_PHYSICIAN = 'ReferringPhysicianName'

DCMHEADER_MANUFACTURER = 'Manufacturer'
DCMHEADER_STATION_NAME = 'StationName'

DCMHEADER_REQUESTED_PROCEDURE_ID = 'RequestedProcedureID'
DCMHEADER_REQUESTED_PROCEDURE_DESCRIPTION = 'RequestedProcedureDescription'

DCMHEADER_CLINICAL_TRIAL_PROTOCOLID = 'ClinicalTrialProtocolID'
DCMHEADER_CLINICAL_TRIAL_SUBJECTID = 'ClinicalTrialSubjectID'
DCMHEADER_CLINICAL_TRIAL_SPONSOR = 'ClinicalTrialSponsorName'

DCMCODE_IMAGE_POSITION_PATIENT = ('0020', '0032')
DCMHEADER_IMAGE_POSITION_PATIENT = 'ImagePositionPatient'

DCMCODE_IMAGE_ORIENTATION_PATIENT = ('0020', '0037')
DCMHEADER_IMAGE_ORIENTATION_PATIENT = 'ImageOrientationPatient'

DCMHEADER_PATIENT_POSITION = 'PatientPosition'

DCMCODE_MODALITY = ('0008', '0060')
DCMHEADER_MODALITY = 'Modality'

DCMCODE_MODALITIES_IN_STUDY = ('0008', '0061')
DCMHEADER_MODALITIES_IN_STUDY = 'ModalitiesInStudy'

DCMCODE_PROTOCOL_NAME = ('0018', '1030')
DCMHEADER_PROTOCOL_NAME = 'ProtocolName'

DCMCODE_BODY_PART_EXAMINED = ('0018', '0015')
DCMHEADER_BODY_PART_EXAMINED = 'BodyPartExamined'

DCMCODE_INSTANCE_NUMBER = ('0020', '0013')
DCMHEADER_INSTANCE_NUMBER = 'InstanceNumber'

DCMCODE_INSTANCE_CREATION_DATE = ('0008', '0012')
DCMHEADER_INSTANCE_CREATION_DATE = 'InstanceCreationDate'

DCMCODE_INSTANCE_CREATION_TIME = ('0008', '0013')
DCMHEADER_INSTANCE_CREATION_TIME = 'InstanceCreationTime'

DCMCODE_SCANNING_SEQUENCE = ('0018', '0020')
DCMHEADER_SCANNING_SEQUENCE = 'ScanningSequence'

DCMCODE_SEQUENCE_VARIANT = ('0018', '0021')
DCMHEADER_SEQUENCE_VARIANT = 'SequenceVariant'

DCMCODE_SCAN_OPTIONS = ('0018', '0022')
DCMHEADER_SCAN_OPTIONS = 'ScanOptions'

DCMCODE_MR_ACQUISITION_TYPE = ('0018', '0023')
DCMHEADER_MR_ACQUISITION_TYPE = 'MRAcquisitionType'

DCMCODE_SEQUENCE_NAME = ('0018', '0024')
DCMHEADER_SEQUENCE_NAME = 'SequenceName'

DCMCODE_ANGIO_FLAG = ('0018', '0025')
DCMHEADER_ANGIO_FLAG = 'AngioFlag'

DCMCODE_LATERALITY = ('0020', '0060')
DCMHEADER_LATERALITY = 'Laterality'

DCMHEADER_SERIES_NUMBER = 'SeriesNumber'
DCMHEADER_SERIES_TYPE = 'SeriesType'
DCMHEADER_OPERATORS_NAME = 'OperatorsName'

DCMHEADER_IMAGES_IN_ACQUISITION = 'ImagesInAcquisition'
DCMHEADER_CARDIAC_NUMBER_OF_IMAGES = 'CardiacNumberOfImages'
DCMHEADER_NUMBER_OF_TEMPORAL_POSITIONS = 'NumberOfTemporalPositions'
DCMHEADER_NUMBER_OF_SLICES = 'NumberOfSlices'
DCMHEADER_NUMBER_OF_TIME_SLICES = 'NumberOfTimeSlices'

DCMHEADER_PERFORMED_PROCEDURE_STEP_DESCRIPTION = 'PerformedProcedureStepDescription'
DCMHEADER_ACQUISITION_DEVICE_PROCESSING_DESCRIPTION = 'AcquisitionDeviceProcessingDescription'
DCMHEADER_CONTRAST_BOLUS_AGENT = 'ContrastBolusAgent'

DCMHEADER_SR_PERTINENT_OTHER_EVIDENCE_SEQUENCE = 'PertinentOtherEvidenceSequence'
DCMHEADER_SR_REF_SERIES_SEQ = 'ReferencedSeriesSequence'
DCMHEADER_SR_REF_INSTANCE_SEQ = 'ReferencedInstanceSequence'
DCMHEADER_SR_REF_SOP_SEQ = 'ReferencedSOPSequence'
DCMHEADER_SR_DERIVATION_IMAGE_SEQ = 'DerivationImageSequence'
DCMHEADER_SR_SOURCE_IMAGE_SEQ = 'SourceImageSequence'

DCMHEADER_SR_REF_INSTANCE_UID = 'ReferencedSOPInstanceUID'

DCM_PATIENT_POSITION_HFP = 'HFP'
DCM_PATIENT_POSITION_HFS = 'HFS'
DCM_PATIENT_POSITION_HFDR = 'HDFR'
DCM_PATIENT_POSITION_HFDL = 'HFDL'
DCM_PATIENT_POSITION_FFP = 'FFP'
DCM_PATIENT_POSITION_FFS = 'FFS'
DCM_PATIENT_POSITION_FFDR = 'FFDR'
DCM_PATIENT_POSITION_FFDL = 'FFDL'

DCM_PATIENT_POSITION_LABELS = {
	DCM_PATIENT_POSITION_HFP: 'Head First Prone',
	DCM_PATIENT_POSITION_HFS: 'Head First Supine',
	DCM_PATIENT_POSITION_HFDR: 'Head First Decubitus Right',
	DCM_PATIENT_POSITION_HFDL: 'Head First Decubitus Left',
	DCM_PATIENT_POSITION_FFP: 'Feet First Prone',
	DCM_PATIENT_POSITION_FFS: 'Feet First Supine',
	DCM_PATIENT_POSITION_FFDR: 'Feet First Decubitus Right',
	DCM_PATIENT_POSITION_FFDL: 'Feet First Decubitus Left',
}

DCM_DATETIME_STRFORMAT = '%Y%m%d%H%M%S.%f'
DCM_DATE_STRFORMAT = '%Y%m%d'
DCM_DATE_STRFORMAT_ALT1 = '%Y-%m%d'
DCM_DATE_STRFORMAT_ALT2 = '%m/%d/%Y'
DCM_TIME_STRFORMAT = '%H%M%S.%f'
DCM_TIME_STRFORMAT_ALT1 = '%H%M%S'


DCM_FILE_EXTENSION = 'dcm'
DCM_EXTENSIONS_DEFAULT = ['*.dcm', '*.DCM', '*.DICOM', '*.dicom', 'IM*']
DCM_EXTENSIONS_ALL_FILES = ['*']
DCM_MODALITY_MR = 'MR'
DCM_MODALITIES_MRI = ['MR', 'MRI', 'MR\\SD']

DCM_MODALITY_SR = 'SR'
DCM_MODALITY_SEG = 'SEG'

DCM_ORIGINAL_ATTRIBUTES_SEQUENCE = 'OriginalAttributesSequence'
DCM_MODIFIED_ATTRIBUTES_SEQUENCE = 'ModifiedAttributesSequence'
DCM_ATTRIBUTE_MOD_DATETIME = 'AttributeModificationDateTime'
DCM_MODIFYING_SYSTEM = 'ModifyingSystem'
DCM_SOURCE_PREVIOUS_VALUES = 'SourceOfPreviousValues'
DCM_MODIFICATION_REASON = 'ReasonForTheAttributeModification'

DCM_MODIFY_CODE_COERCE = 'COERCE'
DCM_MODIFY_CODE_CORRECT = 'CORRECT'


# Environment variable names
SONADOR_ACCESS_ID = 'SONADOR_ACCESS_ID'
SONADOR_SECRET_KEY = 'SONADOR_SECRET_KEY'
SONADOR_URL = 'SONADOR_URL'
SONADOR_APITOKEN = 'SONADOR_APITOKEN'
SONADOR_INTERNAL_DNS = 'SONADOR_INTERNAL_DNS'
SONADOR_IMAGING_SERVER = 'SONADOR_IMAGING_SERVER'
SONADOR_SERVICE_CLIENT_ID = 'SONADOR_SERVICE_CLIENT_ID'


# Functional testing globals
from client.utils.logs import LOGGING_LEVELS

TESTING_VERBOSITY = {
	'debug': 3,
	'info': 2,
	'warning': 1,
	'error': 0,
	'critical': 0,
}


# Header cache constants and data classes
DCM_CONTENT_TYPE = 'application/octet-stream'

DicomMetaKey = namedtuple('DicomMetaKey', ('resource', 'header', 'uid'))
DicomMeta = namedtuple('DicomMeta', ('description', 'modality'))



