from .base import DCMHEADER_PATIENT_SEX, \
	DCM_PATIENT_SEX_MALE, DCM_PATIENT_SEX_FEMALE, DCM_PATIENT_SEX_OTHER, DCM_PATIENT_SEX_UNKNOWN


FHIR_UNKNOWN = 'unknown'

# FHIR Use Codes
FHIR_USE_USUAL = 'usual'
FHIR_USE_OFFICIAL = 'official'
FHIR_USE_TEMP = 'temp'
FHIR_USE_SECONDARY = 'secondary'
FHIR_USE_BILLING = 'billing'

# Address Use Codes
FHIR_ADDR_USE_HOME = 'home'
FHIR_ADDR_USE_WORK = 'work'

# Support Codes
FHIR_ID_USE_CODES = (
	FHIR_USE_USUAL, FHIR_USE_OFFICIAL, FHIR_USE_TEMP, FHIR_USE_SECONDARY)
FHIR_NAME_USE_CODES = (
	FHIR_USE_USUAL, FHIR_USE_OFFICIAL, FHIR_USE_TEMP, 'nickname', 'anonymous', 'old', 'maiden')
FHIR_ADDR_USER_CODES = (
	FHIR_ADDR_USE_HOME, FHIR_ADDR_USE_WORK, FHIR_USE_TEMP, 'old', FHIR_USE_BILLING)

# Status Codes
FHIR_STATUS_DRAFT = 'draft'
FHIR_STATUS_ACTIVE = 'active'
FHIR_STATUS_REVOKED = 'revoked'
FHIR_STATUS_COMPLETE = 'complete'
FHIR_STATUS_ENTERED_IN_ERROR = 'entered-in-error'

FHIR_REQUEST_STATUS = (
	FHIR_STATUS_DRAFT, FHIR_STATUS_ACTIVE, FHIR_STATUS_REVOKED, FHIR_STATUS_COMPLETE, 
	FHIR_STATUS_ENTERED_IN_ERROR, FHIR_UNKNOWN)


# Supported sex/gender codes: DICOM <-> FHIR
FHIR_GENDER_DCM_MAP = {
	DCM_PATIENT_SEX_MALE: 'male',
	DCM_PATIENT_SEX_FEMALE: 'female',
	DCM_PATIENT_SEX_UNKNOWN: FHIR_UNKNOWN,
	DCM_PATIENT_SEX_OTHER: 'other',
}
DCM_GENDER_FHIR_MAP = dict((v,k) for k,v in FHIR_GENDER_DCM_MAP.items())