from .base import DCMHEADER_FRAME_OF_REFERENCE_UID, DCMHEADER_SLICE_THICKNESS, DCMHEADER_PATIENT_POSITION, \
	DCMHEADER_IMAGE_POSITION_PATIENT, DCMHEADER_IMAGE_ORIENTATION_PATIENT
from .media import ANATOMY_BONE_HEXCOLOR_PRIMARY, ANATOMY_BONE_HEXCOLOR, ANATOMY_BONE_THORAX_HEXCOLOR_PRIMARY, \
	ANATOMY_BONE_LOWER_LIMB_HEXCOLOR_PRIMARY, ANATOMY_BONE_LOWER_LIMB_HEXCOLOR, \
	ANATOMY_BONE_PELVIS_HEXCOLOR_PRIMARY, ANATOMY_BONE_THORAX_HEXCOLOR, \
	ANATOMY_CARTILAGE_HEXCOLOR_PRIMARY, ANATOMY_CARTILAGE_HEXCOLOR, DCMHEADER_RECOMMENDED_DISPLAY_COLOR_VALUE, \
	DCM_MEDIA_PATIENT_TAGS, DCM_MEDIA_STUDY_TAGS, DCM_MEDIA_CLINICAL_TRIAL_TAGS


# Sets of DICOM tags for STL files: patient, study, series, clinical trial
M3D_DCM_PATIENT_TAGS = DCM_MEDIA_PATIENT_TAGS
M3D_DCM_STUDY_TAGS = DCM_MEDIA_STUDY_TAGS
M3D_DCM_SERIES_TAGS = set((
    DCMHEADER_FRAME_OF_REFERENCE_UID, DCMHEADER_SLICE_THICKNESS,
    DCMHEADER_PATIENT_POSITION, DCMHEADER_IMAGE_POSITION_PATIENT, DCMHEADER_IMAGE_ORIENTATION_PATIENT))
M3D_CLINICAL_TRIAL_TAGS = DCM_MEDIA_CLINICAL_TRIAL_TAGS