'''	Global constants to aid in the encoding of DICOM encapsulated medical 3D (M3D)
	series within Sonador. Module includes:

	*	Totalsegmentator anatomic labels and display color values. Totalsegmentator
		provides a set of 117 (as of Febraury 2025) labels describing a comprehensive
		set of anatomic structures. These labels are used within Sonador and the supporting
		ecosystem of tools to reference anatomy and align workflows from AI based
		segmentation to the manufacturing of patient specific instrucmentation in a consistent fashion.

'''
from collections import OrderedDict

from .base import DCMHEADER_FRAME_OF_REFERENCE_UID, DCMHEADER_SLICE_THICKNESS, DCMHEADER_PATIENT_POSITION, \
	DCMHEADER_IMAGE_POSITION_PATIENT, DCMHEADER_IMAGE_ORIENTATION_PATIENT
from .media import DCM_MEDIA_PATIENT_TAGS, DCM_MEDIA_STUDY_TAGS, DCM_MEDIA_CLINICAL_TRIAL_TAGS, \
	ANATOMY_BONE_HEXCOLOR_PRIMARY, ANATOMY_BONE_HEXCOLOR, ANATOMY_BONE_THORAX_HEXCOLOR_PRIMARY, \
	ANATOMY_BONE_LOWER_LIMB_HEXCOLOR_PRIMARY, ANATOMY_BONE_LOWER_LIMB_HEXCOLOR, \
	ANATOMY_BONE_PELVIS_HEXCOLOR_PRIMARY, ANATOMY_BONE_THORAX_HEXCOLOR, \
	ANATOMY_CARTILAGE_HEXCOLOR_PRIMARY, ANATOMY_CARTILAGE_HEXCOLOR, DCMHEADER_RECOMMENDED_DISPLAY_COLOR_VALUE, \
	ANATOMY_BONE_STERNUM_HEXCOLOR, ANATOMY_BONE_RIB_HEXCOLOR, ANATOMY_MUSCLE_HIP_HEXCOLOR, ANATOMY_MUSCLE_HIP_MEDIUS_HEXCOLOR, \
	ANATOMY_SPINAL_CORD_HEXCOLOR, ANATOMY_BONE_HIP_HEXCOLOR, ANATOMY_BONE_SHOULDER_HEXCOLOR, ANATOMY_VENA_CAVA_HEXCOLOR, \
	ANATOMY_VEIN_ILIAC_HEXCOLOR, ANATOMY_ARTERY_ILIAC_HEXCOLOR, ANATOMY_VEIN_PULMONARY_HEXCOLOR, ANATOMY_AORTA_HEXCOLOR, \
	ANATOMY_HEART_HEXCOLOR, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR, ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR, ANATOMY_VERTEBRAE_SACRUM, \
	ANATOMY_GI_COLON_HEXCOLOR, ANATOMY_GI_DUODENUM_HEXCOLOR, ANATOMY_GI_SMALL_BOWEL_HEXCOLOR, ANATOMY_GI_ESOPHAGUS_HEXCOLOR, \
	ANATOMY_LUNG_LOWER_LOBE_HEXCOLOR, ANATOMY_LUNG_UPPER_LOBE_HEXCOLOR, ANATOMY_LUNG_MIDDLE_LOBE_HEXCOLOR, \
	ANATOMY_ADRENAL_GLAND_HEXCOLOR, ANATOMY_PANCREAS_HEXCOLOR, ANATOMY_STOMACH_HEXCOLOR, ANATOMY_LIVER_HEXCOLOR, \
	ANATOMY_GALLBLADDER_HEXCOLOR, ANATOMY_KIDNEY_HEXCOLOR, ANATOMY_SPLEEN_HEXCOLOR, ANATOMY_BONE_LEG_HEXCOLOR

# Sets of DICOM tags for STL files: patient, study, series, clinical trial
M3D_DCM_PATIENT_TAGS = DCM_MEDIA_PATIENT_TAGS
M3D_DCM_STUDY_TAGS = DCM_MEDIA_STUDY_TAGS
M3D_DCM_SERIES_TAGS = set((
    DCMHEADER_FRAME_OF_REFERENCE_UID, DCMHEADER_SLICE_THICKNESS,
    DCMHEADER_PATIENT_POSITION, DCMHEADER_IMAGE_POSITION_PATIENT, DCMHEADER_IMAGE_ORIENTATION_PATIENT))
M3D_CLINICAL_TRIAL_TAGS = DCM_MEDIA_CLINICAL_TRIAL_TAGS


# Total Segmentator Labels
TOTALSEGMENTATOR_SPLEEN = 'spleen'
TOTALSEGMENTATOR_KIDNEY_RIGHT = 'kidney_right'
TOTALSEGMENTATOR_KIDNEY_LEFT = 'kidney_left'
TOTALSEGMENTATOR_LIVER = 'liver'
TOTALSEGMENTATOR_STOMACH = 'stomach'
TOTALSEGMENTATOR_PANCREAS = 'pancreas'
TOTALSEGMENTATOR_GALLBLADDER = 'gallbladder'

# Lung
TOTALSEGMENTATOR_ADRENAL_GLAND_RIGHT = 'adrenal_gland_right'
TOTALSEGMENTATOR_ADRENAL_GLAND_LEFT = 'adrenal_gland_left'
TOTALSEGMENTATOR_LUNG_UPPER_LOBE_LEFT = 'lung_upper_lobe_left'
TOTALSEGMENTATOR_LUNG_LOWER_LOBE_LEFT = 'lung_lower_lobe_left'
TOTALSEGMENTATOR_LUNG_UPPER_LOBE_RIGHT = 'lung_upper_lobe_right'
TOTALSEGMENTATOR_LUNG_MIDDLE_LOBE_RIGHT = 'lung_middle_lobe_right'
TOTALSEGMENTATOR_LUNG_LOWER_LOBE_RIGHT = 'lung_lower_lobe_right'

# Gastrointestinal
TOTALSEGMENTATOR_ESOPHAGUS = 'esophagus'
TOTALSEGMENTATOR_SMALL_BOWEL = 'small_bowel'
TOTALSEGMENTATOR_DUODENUM = 'duodenum'
TOTALSEGMENTATOR_COLON = 'colon'
TOTALSEGMENTATOR_SACRUM = 'sacrum'

# Vertebra
TOTALSEGMENTATOR_VERTEBRA_S1 = 'vertebrae_S1'
TOTALSEGMENTATOR_VERTEBRA_L5 = 'vertebrae_L5'
TOTALSEGMENTATOR_VERTEBRA_L4 = 'vertebrae_L4'
TOTALSEGMENTATOR_VERTEBRA_L3 = 'vertebrae_L3'
TOTALSEGMENTATOR_VERTEBRA_L2 = 'vertebrae_L2'
TOTALSEGMENTATOR_VERTEBRA_L1 = 'vertebrae_L1'
TOTALSEGMENTATOR_VERTEBRA_T12 = 'vertebrae_T12'
TOTALSEGMENTATOR_VERTEBRA_T11 = 'vertebrae_T11'
TOTALSEGMENTATOR_VERTEBRA_T10 = 'vertebrae_T10'
TOTALSEGMENTATOR_VERTEBRA_T9 = 'vertebrae_T9'
TOTALSEGMENTATOR_VERTEBRA_T8 = 'vertebrae_T8'
TOTALSEGMENTATOR_VERTEBRA_T7 = 'vertebrae_T7'

# Cardiovascular
TOTALSEGMENTATOR_HEART = 'heart'
TOTALSEGMENTATOR_AORTA = 'aorta'
TOTALSEGMENTATOR_PULMONARY_VEIN = 'pulmonary_vein'
TOTALSEGMENTATOR_PULMONARY_INFERIOR_VENA_CAVA = 'inferior_vena_cava'
TOTALSEGMENTATOR_PORTAL = 'portal_vein_and_splenic_vein'
TOTALSEGMENTATOR_ILIAC_ARTERY_LEFT = 'iliac_artery_left'
TOTALSEGMENTATOR_ILIAC_ARTERY_RIGHT = 'iliac_artery_right'
TOTALSEGMENTATOR_ILIAC_VENA_LEFT = 'iliac_vena_left'
TOTALSEGMENTATOR_ILIAC_VENA_RIGHT = 'iliac_vena_right'

# Scapula and Hip
TOTALSEGMENTATOR_SCAPULA_LEFT = 'scapula_left'
TOTALSEGMENTATOR_SCAPULA_RIGHT = 'scapula_right'
TOTALSEGMENTATOR_HIP_LEFT = 'hip_left'
TOTALSEGMENTATOR_HIP_RIGHT = 'hip_right'
TOTALSEGMENTATOR_SPINAL_CORD = 'spinal_cord'
TOTALSEGMENTATOR_GLUTEUS_MAXIMUS_RIGHT = 'gluteus_maximus_right'
TOTALSEGMENTATOR_GLUTEUS_MEDIUS_LEFT = 'gluteus_medius_left'
TOTALSEGMENTATOR_GLUTEUS_MEDIUS_RIGHT = 'gluteus_medius_right'
TOTALSEGMENTATOR_ILIOPSOAS_LEFT = 'iliopsoas_left'
TOTALSEGMENTATOR_ILIOPSOAS_RIGHT = 'iliopsoas_right'

# Ribcage
TOTALSEGMENTATOR_RIB_LEFT_5 = 'rib_left_5'
TOTALSEGMENTATOR_RIB_LEFT_6 = 'rib_left_6'
TOTALSEGMENTATOR_RIB_LEFT_7 = 'rib_left_7'
TOTALSEGMENTATOR_RIB_LEFT_8 = 'rib_left_8'
TOTALSEGMENTATOR_RIB_LEFT_9 = 'rib_left_9'
TOTALSEGMENTATOR_RIB_LEFT_10 = 'rib_left_10'
TOTALSEGMENTATOR_RIB_LEFT_11 = 'rib_left_11'
TOTALSEGMENTATOR_RIB_LEFT_12 = 'rib_left_12'
TOTALSEGMENTATOR_RIB_RIGHT_5 = 'rib_right_5'
TOTALSEGMENTATOR_RIB_RIGHT_6 = 'rib_right_6'
TOTALSEGMENTATOR_RIB_RIGHT_7 = 'rib_right_7'
TOTALSEGMENTATOR_RIB_RIGHT_8 = 'rib_right_8'
TOTALSEGMENTATOR_RIB_RIGHT_9 = 'rib_right_9'
TOTALSEGMENTATOR_RIB_RIGHT_10 = 'rib_left_10'
TOTALSEGMENTATOR_RIB_RIGHT_11 = 'rib_left_11'
TOTALSEGMENTATOR_RIB_RIGHT_12 = 'rib_left_12'
TOTALSEGMENTATOR_STERNUM = 'sternum'
TOTALSEGMENTATOR_COSTAL_CARTILAGE = 'costal_cartilages'

# Cancer / Growths
TOTALSEGMENTATOR_CYST = 'cyst'

# Musculoskeletal / Appendicular Bones
TOTALSEGMENTATOR_FEMUR_LEFT = 'femur_left'
TOTALSEGMENTATOR_FEMUR_RIGHT = 'femur_right'
TOTALSEGMENTATOR_APPENDICULAR_FEMUR = 'femur'
TOTALSEGMENTATOR_APPENDICULAR_TIBIA = 'tibia'
TOTALSEGMENTATOR_APPENDICULAR_PATELLA = 'patella'
TOTALSEGMENTATOR_APPENDICULAR_FIBULA = 'fibula'
TOTALSEGMENTATOR_APPENDICULAR_TARSAL = 'tarsal'
TOTALSEGMENTATOR_APPENDICULAR_METATARSAL = 'metatarsal'
TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_FEEET = 'phalanges_feet'
TOTALSEGMENTATOR_APPENDICULAR_ULNA = 'ulna'
TOTALSEGMENTATOR_APPENDICULAR_RADIUS = 'radius'
TOTALSEGMENTATOR_APPENDICULAR_CARPAL = 'carpal'
TOTALSEGMENTATOR_APPENDICULAR_METACARPAL = 'metacarpal'
TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_HAND = 'phalanges_hand'


# Totalsegmentator Colors
TOTALSEGMENTATOR_COLORS = OrderedDict((

	# Abdominal Organs
	(TOTALSEGMENTATOR_SPLEEN, ANATOMY_SPLEEN_HEXCOLOR),
	(TOTALSEGMENTATOR_KIDNEY_RIGHT, ANATOMY_KIDNEY_HEXCOLOR),
	(TOTALSEGMENTATOR_KIDNEY_LEFT, ANATOMY_KIDNEY_HEXCOLOR),
	(TOTALSEGMENTATOR_GALLBLADDER, ANATOMY_GALLBLADDER_HEXCOLOR),
	(TOTALSEGMENTATOR_LIVER, ANATOMY_LIVER_HEXCOLOR),
	(TOTALSEGMENTATOR_PANCREAS, ANATOMY_PANCREAS_HEXCOLOR),
	(TOTALSEGMENTATOR_ADRENAL_GLAND_LEFT, ANATOMY_ADRENAL_GLAND_HEXCOLOR),
	(TOTALSEGMENTATOR_ADRENAL_GLAND_RIGHT, ANATOMY_ADRENAL_GLAND_HEXCOLOR),

	# Lungs and Respiratory
	(TOTALSEGMENTATOR_LUNG_UPPER_LOBE_LEFT, ANATOMY_LUNG_UPPER_LOBE_HEXCOLOR),	
	(TOTALSEGMENTATOR_LUNG_LOWER_LOBE_LEFT, ANATOMY_LUNG_LOWER_LOBE_HEXCOLOR),
	(TOTALSEGMENTATOR_LUNG_UPPER_LOBE_RIGHT, ANATOMY_LUNG_UPPER_LOBE_HEXCOLOR),
	(TOTALSEGMENTATOR_LUNG_MIDDLE_LOBE_RIGHT, ANATOMY_LUNG_MIDDLE_LOBE_HEXCOLOR),
	(TOTALSEGMENTATOR_LUNG_LOWER_LOBE_RIGHT, ANATOMY_LUNG_LOWER_LOBE_HEXCOLOR),
	
	# Gastrointestinal
	(TOTALSEGMENTATOR_ESOPHAGUS, ANATOMY_GI_ESOPHAGUS_HEXCOLOR),
	(TOTALSEGMENTATOR_STOMACH, ANATOMY_STOMACH_HEXCOLOR),
	(TOTALSEGMENTATOR_SMALL_BOWEL, ANATOMY_GI_SMALL_BOWEL_HEXCOLOR),
	(TOTALSEGMENTATOR_DUODENUM, ANATOMY_GI_DUODENUM_HEXCOLOR),
	(TOTALSEGMENTATOR_COLON, ANATOMY_GI_COLON_HEXCOLOR),
	
	# Vertebrae and Spinal Column
	(TOTALSEGMENTATOR_VERTEBRA_S1, ANATOMY_VERTEBRAE_SACRUM),
	(TOTALSEGMENTATOR_VERTEBRA_L1, ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_L2, ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_L3, ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_L4, ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_L5, ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_T7, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_T8, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_T9, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_T10, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_T11, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR),
	(TOTALSEGMENTATOR_VERTEBRA_T12, ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR),
	
	# Central Circulatory System
	(TOTALSEGMENTATOR_AORTA, ANATOMY_AORTA_HEXCOLOR),
	(TOTALSEGMENTATOR_PULMONARY_VEIN, ANATOMY_VEIN_PULMONARY_HEXCOLOR),
	(TOTALSEGMENTATOR_ILIAC_ARTERY_LEFT, ANATOMY_ARTERY_ILIAC_HEXCOLOR),
	(TOTALSEGMENTATOR_ILIAC_ARTERY_RIGHT, ANATOMY_ARTERY_ILIAC_HEXCOLOR),
	(TOTALSEGMENTATOR_PULMONARY_INFERIOR_VENA_CAVA, ANATOMY_VENA_CAVA_HEXCOLOR),
	(TOTALSEGMENTATOR_PORTAL, ANATOMY_VENA_CAVA_HEXCOLOR),
	(TOTALSEGMENTATOR_ILIAC_VENA_LEFT, ANATOMY_VEIN_ILIAC_HEXCOLOR),
	(TOTALSEGMENTATOR_ILIAC_VENA_RIGHT, ANATOMY_VEIN_ILIAC_HEXCOLOR),
	
	# Hip and Shoulder Bones
	(TOTALSEGMENTATOR_SCAPULA_LEFT, ANATOMY_BONE_SHOULDER_HEXCOLOR),
	(TOTALSEGMENTATOR_SCAPULA_RIGHT, ANATOMY_BONE_SHOULDER_HEXCOLOR),
	(TOTALSEGMENTATOR_HIP_LEFT, ANATOMY_BONE_HIP_HEXCOLOR),
	(TOTALSEGMENTATOR_HIP_RIGHT, ANATOMY_BONE_HIP_HEXCOLOR),
	
	# Spinal Cord
	(TOTALSEGMENTATOR_SPINAL_CORD, ANATOMY_SPINAL_CORD_HEXCOLOR),
	
	# Hip and Pelvis Musculature
	(TOTALSEGMENTATOR_GLUTEUS_MAXIMUS_RIGHT, ANATOMY_MUSCLE_HIP_HEXCOLOR),
	(TOTALSEGMENTATOR_GLUTEUS_MEDIUS_LEFT, ANATOMY_MUSCLE_HIP_MEDIUS_HEXCOLOR),
	(TOTALSEGMENTATOR_GLUTEUS_MEDIUS_RIGHT, ANATOMY_MUSCLE_HIP_MEDIUS_HEXCOLOR),
	(TOTALSEGMENTATOR_ILIOPSOAS_LEFT, ANATOMY_MUSCLE_HIP_HEXCOLOR),
	(TOTALSEGMENTATOR_ILIOPSOAS_RIGHT, ANATOMY_MUSCLE_HIP_HEXCOLOR),
	
	# Ribs and Thoracic Cartilage
	(TOTALSEGMENTATOR_RIB_LEFT_5, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_6, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_7, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_8, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_9, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_10, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_11, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_LEFT_12, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_5, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_6, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_7, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_8, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_9, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_10, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_11, ANATOMY_BONE_RIB_HEXCOLOR),
	(TOTALSEGMENTATOR_RIB_RIGHT_12, ANATOMY_BONE_RIB_HEXCOLOR), 
	(TOTALSEGMENTATOR_STERNUM, ANATOMY_BONE_STERNUM_HEXCOLOR),
	(TOTALSEGMENTATOR_COSTAL_CARTILAGE, ANATOMY_CARTILAGE_HEXCOLOR),
))


TOTALSEGMENTATOR_APPENDICULAR = set([
	TOTALSEGMENTATOR_APPENDICULAR_FEMUR, TOTALSEGMENTATOR_APPENDICULAR_TIBIA, TOTALSEGMENTATOR_APPENDICULAR_PATELLA,
	TOTALSEGMENTATOR_APPENDICULAR_FIBULA, TOTALSEGMENTATOR_APPENDICULAR_TARSAL, TOTALSEGMENTATOR_APPENDICULAR_METATARSAL,
	TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_FEEET, TOTALSEGMENTATOR_APPENDICULAR_ULNA, TOTALSEGMENTATOR_APPENDICULAR_RADIUS,
	TOTALSEGMENTATOR_APPENDICULAR_CARPAL, TOTALSEGMENTATOR_APPENDICULAR_METACARPAL, TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_HAND,
])

TOTALSEGMENTATOR_APPENDICULAR_MR = set([
	TOTALSEGMENTATOR_APPENDICULAR_PATELLA, TOTALSEGMENTATOR_APPENDICULAR_TIBIA, TOTALSEGMENTATOR_APPENDICULAR_FIBULA,
	TOTALSEGMENTATOR_APPENDICULAR_TARSAL, TOTALSEGMENTATOR_APPENDICULAR_METATARSAL, TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_FEEET, 
	TOTALSEGMENTATOR_APPENDICULAR_ULNA, TOTALSEGMENTATOR_APPENDICULAR_RADIUS,
])


TOTALSEGMENTATOR_APPENDICULAR_COLORS = OrderedDict((
	(TOTALSEGMENTATOR_APPENDICULAR_FEMUR, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_TIBIA, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_PATELLA, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_FIBULA, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_TARSAL, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_METATARSAL, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_FEEET, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_ULNA, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_RADIUS, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_CARPAL, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_METACARPAL, ANATOMY_BONE_LEG_HEXCOLOR),
	(TOTALSEGMENTATOR_APPENDICULAR_PHALANGES_HAND, ANATOMY_BONE_LEG_HEXCOLOR),
))
