'''	Global constants to aid in the encoding of DICOM encapculated media within Sonador.
'''
from .base import DCMHEADER_PATIENT_ID, DCMHEADER_PATIENT_NAME, \
		DCMHEADER_PATIENT_SEX, DCMHEADER_PATIENT_WEIGHT, DCMHEADER_PATIENT_BIRTHDATE, \
	DCMHEADER_STUDY_INSTANCE_UID, DCMHEADER_STUDY_ID, DCMHEADER_STUDY_DATE, DCMHEADER_STUDY_TIME, \
		DCMHEADER_STUDY_DESCRIPTION, DCMHEADER_REFERRING_PHYSICIAN, DCMHEADER_ACCESSION_NUMBER, \
	DCMHEADER_SOP_CLASS_UID, DCMHEADER_SERIES_INSTANCE_UID, DCMHEADER_SERIES_DATE, DCMHEADER_SERIES_TIME, \
		DCMHEADER_SERIES_DESCRIPTION, DCMHEADER_SERIES_NUMBER, DCMHEADER_MODALITY, DCM_MODALITY_MR, \
		DCMHEADER_FRAME_OF_REFERENCE_UID, DCMHEADER_PATIENT_POSITION, DCMHEADER_IMAGE_POSITION_PATIENT, \
		DCMHEADER_SLICE_THICKNESS, DCMHEADER_IMAGE_ORIENTATION_PATIENT, \
		DCMHEADER_SR_SOP_CLASS_UID, \
	DCMHEADER_CLINICAL_TRIAL_SERIES_ID, DCMHEADER_CLINICAL_TRIAL_PROTOCOLID, DCMHEADER_CLINICAL_TRIAL_SUBJECTID, \
		DCMHEADER_CLINICAL_TRIAL_SPONSOR, DCMHEADER_CLINICAL_TRIAL_COORDINATING_CENTER_NAME, \
		DCMHEADER_CLINICAL_TRIAL_TIMEPOINT_ID, \
	DCMHEADER_INSTANCE_NUMBER, DCMHEADER_PRIMARY_ANATOMIC_STRUCTURE_SEQUENCE, \
		DCMHEADER_CONTENT_DATE, DCMHEADER_CONTENT_TIME, DCMHEADER_SR_REF_SERIES_SEQ, \
	DCMHEADER_ENCAPSULATED_DOCUMENT_TITLE, DCMHEADER_CONTENT_DESCRIPTION
from .base import DCM_MODALITY_DOC, DCM_MODALITY_M3D

DCMCODE_RECOMMENDED_DISPLAY_COLOR_VALUE = ('0062', '000d')
DCMHEADER_RECOMMENDED_DISPLAY_COLOR_VALUE = 'RecommendedDisplayCIELabValue'

DCMCODE_SEGMENT_SEQUENCE = ('0062', '0002')
DCMHEADER_SEGMENT_SEQUENCE = 'SegmentSequence'

DCMCODE_SEGMENT_NUMBER = ('0062', '0004')
DCMHEADER_SEGMENT_NUMBER = 'SegmentNumber'

DCMCODE_SEGMENT_LABEL = ('0062', '0005')
DCMHEADER_SEGMENT_LABEL = 'SegmentLabel'

DCMEDIA_M3D_MODALITY = DCM_MODALITY_M3D


# SOP, mimetype, and modality for encapsulated PDF
DCMEDIA_ENCAPSULATED_PDF_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.1'
DCMEDIA_PDF_MIMETYPE = 'application/pdf'
DCMEDIA_PDF_MODALITY = DCM_MODALITY_DOC
DCMEDIA_PDF_EXTENSION = '.pdf'


# OBJ, mimetype, and modality for encapsulated OBJ (and other 3D files)
DCMEDIA_ENCAPSULATED_STL_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.3'
DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_CT = '1.2.840.10008.5.1.4.1.1.2.1'
DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_MRI = '1.2.840.10008.5.1.4.1.1.4.1'
DCMEDIA_STL_MIMETPYE = 'model/stl'
DCMEDIA_STL_MODALITY = DCMEDIA_M3D_MODALITY
DCMEDIA_STL_EXTENSION = '.stl'

DCMEDIA_SUPPORTED_STL_SOP_CLASSES = (
	DCMEDIA_ENCAPSULATED_STL_SOP_CLASS, DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_CT, DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_MRI)

DCMEDIA_ENCAPSULATED_OBJ_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.4'
DCMEDIA_OBJ_MIMETYPE = 'model/obj'
DCMEDIA_OBJ_MODALITY = DCMEDIA_STL_MODALITY
DCMEDIA_OBJ_EXTENSION = '.obj'

DCMEDIA_GLB_MIMETYPE = 'model/gltf-binary'
DCMEDIA_GLB_MODALITY = DCMEDIA_STL_MODALITY
DCMEDIA_GLB_EXTENSION = '.glb'

DCMEDIA_ENCAPSULATED_MTL_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.5 '
DCMEDIA_MTL_MIMETYPE = 'model/mtl'
DCMEDIA_MTL_MODALITY = DCMEDIA_STL_MODALITY
DCMEDIA_MTL_EXTENSION = '.mtl'


# Sets of DICOM Tags for media files: patient, study, series, and clinical trial
DCM_MEDIA_PATIENT_TAGS = set((
	DCMHEADER_PATIENT_ID, DCMHEADER_PATIENT_NAME, DCMHEADER_PATIENT_SEX, DCMHEADER_PATIENT_WEIGHT, DCMHEADER_PATIENT_BIRTHDATE))
DCM_MEDIA_STUDY_TAGS = set((
	DCMHEADER_STUDY_INSTANCE_UID, DCMHEADER_STUDY_ID, DCMHEADER_ACCESSION_NUMBER, DCMHEADER_STUDY_DESCRIPTION, 
	DCMHEADER_STUDY_DATE, DCMHEADER_STUDY_TIME, DCMHEADER_REFERRING_PHYSICIAN))
DCM_MEDIA_CLINICAL_TRIAL_TAGS = set((
	DCMHEADER_CLINICAL_TRIAL_SERIES_ID, DCMHEADER_CLINICAL_TRIAL_PROTOCOLID, DCMHEADER_CLINICAL_TRIAL_SUBJECTID, 
	DCMHEADER_CLINICAL_TRIAL_SPONSOR, DCMHEADER_CLINICAL_TRIAL_COORDINATING_CENTER_NAME, DCMHEADER_CLINICAL_TRIAL_TIMEPOINT_ID))

# Sets of DICOM tags for encapsulated document files: patient, study, series, clinical trial
ENCAPSULATED_DOC_DCM_PATIENT_TAGS = DCM_MEDIA_PATIENT_TAGS
ENCAPSULATED_DOC_DCM_STUDY_TAGS = DCM_MEDIA_STUDY_TAGS
ENCAPSULATED_DOC_CLINICAL_TRIAL_TAGS = DCM_MEDIA_CLINICAL_TRIAL_TAGS


# Anatomical Display Colors
ANATOMY_BONE_HEXCOLOR_PRIMARY = '#f1d691'
ANATOMY_BONE_HEXCOLOR = '#fbf3de'
ANATOMY_BONE_THORAX_HEXCOLOR_PRIMARY = '#ffefac'
ANATOMY_BONE_LOWER_LIMB_HEXCOLOR_PRIMARY = '#ffeeaa'
ANATOMY_BONE_LOWER_LIMB_HEXCOLOR = '#fffae6'
ANATOMY_BONE_PELVIS_HEXCOLOR_PRIMARY = '#d9c683'
ANATOMY_BONE_THORAX_HEXCOLOR = '#fffcee'
ANATOMY_CARTILAGE_HEXCOLOR_PRIMARY = '#6fb8d2'
ANATOMY_CARTILAGE_HEXCOLOR = '#e2f1f6'
ANATOMY_BONE_STERNUM_HEXCOLOR = '#fde89e'
ANATOMY_BONE_RIB_HEXCOLOR = ANATOMY_BONE_STERNUM_HEXCOLOR
ANATOMY_MUSCLE_HIP_HEXCOLOR = '#bc5f4c'
ANATOMY_MUSCLE_HIP_MEDIUS_HEXCOLOR = '#b2694c'
ANATOMY_SPINAL_CORD_HEXCOLOR = '#f4d631'
ANATOMY_BONE_HIP_HEXCOLOR = '#d4bc66'
ANATOMY_BONE_SHOULDER_HEXCOLOR = ANATOMY_BONE_HIP_HEXCOLOR
ANATOMY_VENA_CAVA_HEXCOLOR = '#0097ce'
ANATOMY_VEIN_ILIAC_HEXCOLOR = ANATOMY_VENA_CAVA_HEXCOLOR
ANATOMY_ARTERY_ILIAC_HEXCOLOR = '#d8654f'
ANATOMY_VEIN_PULMONARY_HEXCOLOR = '#ba4d40'
ANATOMY_AORTA_HEXCOLOR = '#e0614c'
ANATOMY_HEART_HEXCOLOR = '#ce6e54'
ANATOMY_VERTEBRAE_THORACIC_HEXCOLOR = '#e2ca86'
ANATOMY_VERTEBRAE_LUMBAR_HEXCOLOR = ANATOMY_BONE_HIP_HEXCOLOR
ANATOMY_VERTEBRAE_SACRUM = ANATOMY_BONE_HIP_HEXCOLOR
ANATOMY_GI_COLON_HEXCOLOR = '#cca88f'
ANATOMY_GI_DUODENUM_HEXCOLOR = '#fffde5'
ANATOMY_GI_SMALL_BOWEL_HEXCOLOR = '#cda78e'
ANATOMY_GI_ESOPHAGUS_HEXCOLOR = '#d3ab8f'
ANATOMY_LUNG_LOWER_LOBE_HEXCOLOR = '#e0baa2'
ANATOMY_LUNG_UPPER_LOBE_HEXCOLOR = '#ac8a73'
ANATOMY_LUNG_MIDDLE_LOBE_HEXCOLOR = '#caa48c'
ANATOMY_ADRENAL_GLAND_HEXCOLOR = '#f9ba96'
ANATOMY_PANCREAS_HEXCOLOR = '#f9b46f'
ANATOMY_STOMACH_HEXCOLOR = '#d88469'
ANATOMY_LIVER_HEXCOLOR = '#dd8265'
ANATOMY_GALLBLADDER_HEXCOLOR = '#8b9662'
ANATOMY_KIDNEY_HEXCOLOR = '#b96653'
ANATOMY_SPLEEN_HEXCOLOR = '#9d6ca2'


# Disease States Display Colors
ANATOMY_CYST_HEXCOLOR = '#cdcd64'