from .base import DCM_MODALITY_DOC

DCMCODE_RECOMMENDED_DISPLAY_COLOR_VALUE = ('0062', '000d')
DCMHEADER_RECOMMENDED_DISPLAY_COLOR_VALUE = 'RecommendedDisplayCIELabValue'

DCMEDIA_M3D_MODALITY = 'M3D'


# SOP, mimetype, and modality for encapsulated PDF
DCMEDIA_ENCAPSULATED_PDF_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.1'
DCMEDIA_PDF_MIMETYPE = 'application/pdf'
DCMEDIA_PDF_MODALITY = DCM_MODALITY_DOC
DCMEDIA_PDF_EXTENSION = '.pdf'


# OBJ, mimetype, and modality for encapsulated OBJ (and other 3D files)
DCMEDIA_ENCAPSULATED_STL_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.3'
DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_CT = '1.2.840.10008.5.1.4.1.1.2.1'
DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_MRI = '1.2.840.10008.5.1.4.1.1.4.1'
DCMEDIA_STL_MIMETPYE = 'model/stl'
DCMEDIA_STL_MODALITY = DCMEDIA_M3D_MODALITY
DCMEDIA_STL_EXTENSION = '.stl'

DCMEDIA_SUPPORTED_STL_SOP_CLASSES = (
	DCMEDIA_ENCAPSULATED_STL_SOP_CLASS, DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_CT, DCMEDIA_ENCAPSULATED_STL_SOP_CLASS_MRI)

DCMEDIA_ENCAPSULATED_OBJ_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.4'
DCMEDIA_OBJ_MIMETYPE = 'model/obj'
DCMEDIA_OBJ_MODALITY = DCMEDIA_STL_MODALITY
DCMEDIA_OBJ_EXTENSION = '.obj'

DCMEDIA_GLB_MIMETYPE = 'model/gltf-binary'
DCMEDIA_GLB_MODALITY = DCMEDIA_STL_MODALITY
DCMEDIA_GLB_EXTENSION = '.glb'

DCMEDIA_ENCAPSULATED_MTL_SOP_CLASS = '1.2.840.10008.5.1.4.1.1.104.5 '
DCMEDIA_MTL_MIMETYPE = 'model/mtl'
DCMEDIA_MTL_MODALITY = DCMEDIA_STL_MODALITY
DCMEDIA_MTL_EXTENSION = '.mtl'