import re
from collections import namedtuple

from pydicom.sr.codedict import codes as dcmcodes

from highdicom.version import __version__ as HIGHDICOM_VERSION
from highdicom.sr.templates import Code, CodedConcept


from .base import DCMHEADER_CODE_VALUE, DCMHEADER_CODING_SCHEME_DESIGNATOR, \
	DCMHEADER_CODING_SCHEME_VERSION, DCMHEADER_CODE_MEANING, \
	DCMHEADER_MAPPING_RESOURCE, DCMHEADER_MAPPING_RESOURCE_UID, \
	DCMHEADER_LONG_CODE_VALUE, DCMHEADER_MAPPING_RESOURCE_NAME, \
	DCMHEADER_CONTEXT_GROUP_VERSION, DCMHEADER_CONTEXT_UID

DCM_CODED_CONCEPT_HEADERS = (DCMHEADER_CODE_VALUE, DCMHEADER_CODING_SCHEME_DESIGNATOR,
	DCMHEADER_CODE_MEANING, DCMHEADER_CODING_SCHEME_VERSION)
DCM_CODED_CONCEPT_MAPPING = {
	'value': DCMHEADER_CODE_VALUE,
	'scheme_designator': DCMHEADER_CODING_SCHEME_DESIGNATOR,
	'meaning': DCMHEADER_CODE_MEANING,
	'scheme_version': DCMHEADER_CODING_SCHEME_VERSION,
}