# Worklist Reviewer Values
SONADOR_WORKLIST_STATUS_APPROVED = 'Approved'
SONADOR_WORKLIST_STATUS_REJECTED = 'Rejected'
SONADOR_WORKLIST_STATUS_UNREAD = 'Unread'
SONADOR_WORKLIST_STATUS_REVIEWED = 'Reviewed'

# DICOM Procedure Step Values
SONADOR_WORKLIST_STATUS_SCHEDULED = 'Scheduled'
SONADOR_WORKLIST_STATUS_INPROGRESS = 'In-progress'
SONADOR_WORKLIST_STATUS_COMPLETED = 'Completed'
SONADOR_WORKLIST_STATUS_CANCELLED = 'Cancelled'
